/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_cs_detector_tools_NativeTools */

#ifndef _Included_ru_cs_detector_tools_NativeTools
#define _Included_ru_cs_detector_tools_NativeTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_cs_detector_tools_NativeTools
 * Method:    releaseResources
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_cs_detector_tools_NativeTools_releaseResources
  (JNIEnv *, jclass);

/*
 * Class:     ru_cs_detector_tools_NativeTools
 * Method:    toRGBA
 * Signature: (II[B[I)V
 */
JNIEXPORT void JNICALL Java_ru_cs_detector_tools_NativeTools_toRGBA
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     ru_cs_detector_tools_NativeTools
 * Method:    initResources
 * Signature: (II[B[I)V
 */
JNIEXPORT void JNICALL Java_ru_cs_detector_tools_NativeTools_initResources__II_3B_3I
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     ru_cs_detector_tools_NativeTools
 * Method:    captureText
 * Signature: (II[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_cs_detector_tools_NativeTools_captureText__II_3B_3I
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     ru_cs_detector_tools_NativeTools
 * Method:    trackText
 * Signature: (II[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_cs_detector_tools_NativeTools_trackText__II_3B_3I
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     ru_cs_detector_tools_NativeTools
 * Method:    initResources
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_ru_cs_detector_tools_NativeTools_initResources__II_3B
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     ru_cs_detector_tools_NativeTools
 * Method:    captureText
 * Signature: (II[B)Lru/cs/detector/tools/Rect;
 */
JNIEXPORT jobject JNICALL Java_ru_cs_detector_tools_NativeTools_captureText__II_3B
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     ru_cs_detector_tools_NativeTools
 * Method:    trackText
 * Signature: (II[B)Lru/cs/detector/tools/Rect;
 */
JNIEXPORT jobject JNICALL Java_ru_cs_detector_tools_NativeTools_trackText__II_3B
  (JNIEnv *, jclass, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
